@startuml
title 処理フロー
start
:オプション読み込み;
:コマンドライン引数読み込み;
if (テンプレートファイルが存在する) then (false)
    :usageを表示する;
    stop
else (true)
end if
if (データファイルが存在する) then (false)
    :ファイルが存在しません;
    stop
else (true)
end if
:データファイル読み込み;
:データファイルを閉じる;
:テンプレートファイルを開く;
while (全てのワークシートデータに対して)
    :シート名を取得する;
    :シートオブジェクトを得る;
    while (全ての置換データに対して)
        :レンジの値を書き換える;
    end while
end while
:データファイルの主ファイル名を得る;
:テンプレートファイルをデータファイルの主ファイル名+xlsxで別名保存する;
:テンプレートファイルを閉じる;
end
@enduml